test_data = """
sesenwnenenewseeswwswswwnenewsewsw
neeenesenwnwwswnenewnwwsewnenwseswesw
seswneswswsenwwnwse
nwnwneseeswswnenewneswwnewseswneseene
swweswneswnenwsewnwneneseenw
eesenwseswswnenwswnwnwsewwnwsene
sewnenenenesenwsewnenwwwse
wenwwweseeeweswwwnwwe
wsweesenenewnwwnwsenewsenwwsesesenwne
neeswseenwwswnwswswnw
nenwswwsewswnenenewsenwsenwnesesenew
enewnwewneswsewnwswenweswnenwsenwsw
sweneswneswneneenwnewenewwneswswnese
swwesenesewenwneswnwwneseswwne
enesenwswwswneneswsenwnewswseenwsese
wnwnesenesenenwwnenwsewesewsesesew
nenewswnwewswnenesenwnesewesw
eneswnwswnwsenenwnwnwwseeswneewsenese
neswnwewnwnwseenwseesewsenwsweewe
wseweeenwnesenwwwswnew
""".strip()

data = """
neesewweeseeseesewseeenwneswe
neneswnenenwnenenwnwenesenenwnwnenenwne
neswnweswseswnesewsesweswwswswneswsew
neneeneneeneewnenweneneeeeswswe
seeeeseseseeeeweeeseneenweeee
swseswwswswswswwswswswswswswneswwswsw
seseswsenwseseseseseseseesenwswswsenwse
seswnesenwsesweseswesenwsesesesewsenwsese
enwwwsewwnwwwwnenw
eeewseeeeseseseeeeseseseeneese
eseneswwseseseseseswsesenwseseseswswwse
nesweeeneneneenenwnenenenwseseeneenew
eseeeeseeneewnwseseenwnweeeene
nwswnwsenwwnewnenwnwnwnwnwnwenwnenwnwnwse
swneseneseseswseswwseneswnwseseesesesesw
wswnwwwwewnwwwwnwwwwwwnwnww
ewwwswwwwnww
wwnwwwwwwwseswwewwwnewsww
swwwnewswwseswswswswswswswswsw
wswwwwnewwwsewwwswwwwwww
nenweseswsesesesenwsewsesewsesenenesesw
swswswnwsenwseseseswseseswsesw
seseewseeseseseesesesesesesesesesese
swesweeeseneeneeeeeeeswenwese
wnwnwnwwwnwnwnwwnwwwnenwnwse
neseeseseseswsenesewesenesewswnwnwse
sweeneswwswswswnwswswsw
eeeeeeweeeeeeeeswenwneeew
swwesewwnwswenenenwnwnewseswwswew
seswswswnwesenwwswswsweeswwenwnwenw
nwnewenwwswnwewsewswnesenwenwwsew
nwnwnwnwswenwnwswsenenwwnwnenwnwseese
wwnewwwwwwnwwwswnwnwnwnw
nwenwwnwnwnwnwnwnwwnwnwnw
sewnenewwnenenwswnwenwnwseneeswnenwne
enewneenwneneeenewswseseneewewne
neneneswnwswneewnenenenwneeneneeneene
nweeeneeneseneneneneneneneeneneee
swwnenwnwnwwnwsenwwnwsewnwnwnwnwnwnenw
wwseswwwwnwneesewwseswnwsenwwwnew
seseswseswneswseswswseswwswseswneswsw
nenenwswnenwswnwneneswswenewewneene
sweswnwwneswseseseneseswseseswneseswsesesw
nwnwnenwnwwsenwnwnwnenwwnwnwswsenwnww
wnewwsenwwsenwwswwwnwwnenwnenww
nwwwwswseswwswnesw
eseeeeeeeeeeeeeswenewee
neeneneeswneneeneneneeenewnwnenenene
wneeswnwwsewenwneneswnwneesewneesw
nwwnwneseswnwwenwwsenwenenwnwseeseww
swnewwswswswswwswswwnwswswswseswwsw
sesenwseswneswswswswswnwswnwseswseeeswsese
nwnwnwswnweseswnwnwnwnenwnwnwne
swsweeeeeneeseeneswneswnwnewsesw
seswseswseseswswseseswseneseweseswsesese
eeneenenenenenesweneneenene
seeseeeeeseeeeeeeeeenwese
nenwnewwswwwnwwswwnwnwneswwsewnw
seseseswsesesesenweeesenwseseseesesese
wwwnesenesweswswnwwwwnwnwnwsewne
swswweseseswswsweseswswswswswseswsww
eneeseseneenwwnwwneneeseeseswnwne
seswswswenesesweseswnwswsesenwwsesw
wwwwswwwwnwwswnwneesewswswsew
wnwseeneswseeeseseeseewwseenwnee
wseeseseseeseseseseseesesesese
seswswseeseseswseswswseswseswnw
wwwwwwwwwewswwswnwnwseswwwwsw
eeeenwsweeeesweeneeeswenene
nwneewnwnewnenwenweneneswsewsenwsw
neeeneneeeeeeeneeeneeeneew
nwnwnenwwnwnwnwnwnwwnwnwnwnwnwnwsenwnw
sweenwnwswnwnwnwnwnwnenewnwsenwneeswnenw
seswseneneswnwswnweseseswsesewsesewswwe
wswwnwsewnewnwwswwewwswwsesewnww
wseswseseswswsesewnenwnwseneseneswsew
swseswwsesenesenwnwswseeswneswswseseswnesw
swnenwneneneenenewnwnenwnwseeswnwwne
senewnwnewseseneeseswswnenwsewwsesese
nwsweswswswseswswsweswswswnwseswswwnwsw
nwnenwnenwswnwnenenenwnwnenwnenwswneneenw
nwnwnwnwnwnwnenesenwnwnenwnenwnwnwnenwnw
wwnewwnwwwwsewwwwnwwwwww
swseneseseswseswseswseseesesesesew
eswswwswswswswwwswswswnenesweswswsw
swneneweneneneneneseneenenweeenene
eseeeseseesesenweseneseesenwnwsewse
eeeeeeeeeeeweeeeeeee
swneesewneenwnenesenenesenenenwwnewne
seseswsewseneneseswseswsewsewseswesese
enweneeneneeneeswneeseeneeee
nenenenwsenwnenwenenwwneneneswnenenesw
seseseeseneneeseseeseesesesewewse
neswseswseseseswswseswwseenwseswswnwswsw
eneneeweeeeneseeeneeeeeewnene
nwenwswesweswenwe
seswswswseswswseswswswswwneswswswswneswsw
enenenenenwnenenenenenenenenesenenene
wseswnewneswwwswswwswewnenewwse
wwseneseweneswneeneeswnwne
wnwwwwwwwewnwwnenwwsewwsww
seneswneneenewswnenenwenweenenenesee
seseeseeswewseeeeenwenwsweene
eneeeneeeeeneneeeneeneswwesenene
newswnwsenwwswenwnewne
nwnwnwnwwnwsenwnwwnwwnwnwnwnwnwnwnwnw
neneeeeneeneneeeeneeeesweee
wnenenwswsewenenwnenwneneswnweenenwwe
nwwsenenwseswwsenwwnewnenwswwnwsenw
wnwwnwwwwewnewwwwwsewwwwswnw
nwnwsenwnweseswwswsenenenwnw
neenenenwnwnenwneneswnenesenenwnenwnenwne
nwwsenewnenwnesene
eeeeeeesewsweeeswenweenwe
swwnewwseseswwswwnwnenewwnwsenese
wwswswseeneswswnwwswswswwswswswswswsw
sewnwnwnenenwenenwnwnwnwsenwswnwnwnwnenwnw
nwnwnenenwneswnwnenwnwswnwneenwnwnenwnwnw
nesenenwnwnwnwenenwnewnwnwnwnenwnwnww
wnesesesweseeeswneseenew
nenwewesenwnewwwnwenewswnwnwseenw
weeseeseeseneseseseeseeseesesee
swwswwwswswswwswwwwswswwwew
nwnenenenenwneswnwnwsenenenenenenenwnwnwnwe
seseseseeseseseseseseeesenwseeswseee
swseseseswseseswseswswsenesesesesesw
nwnenwnesenwnwnenwnwnenenwnwwnwnenwnwnwne
swswswswswseseswsesweseseswnwswswsw
ewwnwwwnwwwswweww
seewsenenwswseswswnwseswseseswneseswsesw
wnewwnwwwwwwwwwwwsewwwww
sesesesesenwseseseseseswseseseesenwnwse
swswswswswswswswswswswswswswsweswswnwsww
swswewseswswwwsewswwnweswswswswnenw
nwsewwnwnwnwnwwnwnwwwwnwnwnwnwnww
wneneseneneneneneesewnenenenenene
eenwseeswswswnweseeseswneeenwnwne
neneneneneneneneneneswswnenenenenenenenene
swswswsesewswswnenwswswswseswswswswseesw
nesenenwseswswswnwswseseswseswsweswseswe
seeswenwsewneswneneswswnwswnwseswsene
nenwnenwnwnwnwnesenenenenenenwwnwnwnwnwnw
wneeneneneeneneneenenenesweneneenene
nwenenwnenenwnwnwnenwnwswseenwswwnesw
neseseneneseswswswwswsenesesw
swswswwnweswsewewswswswswswswswsww
nwswswseseswswseseeswsesesewseseswnesesw
wnenwneswnenenwseenwnwenewnwnenenw
eeeneneneswnenenenenene
swswwswswswswwswweswwswswwnwwwww
nwswnwwnwwnwswnweseswenenwesenwnwnew
seeseseseseeeseseeseseenweeweee
swseseseseseseseswseseneseseseseseswsenw
nenwnenenenenenesenenenwnenenewnene
nenenenweenewneneswnesenenwnesenewne
swswswswwswswswneswswswswswswswsw
nwsesenwnwseseseseweeseseswsesesesese
eeneneneneneseneenenenenwnenenenenene
sweswneswneneseswneenenenwneneswne
eswseeseseeseseseseneseeeseewnee
neneeeweeeneneneeneneneeneeese
sweswswneswwwwswswswnwswnwseswswswwsw
wnwseseseeswnwenwsesweseweseseswnwse
seseeeswsewseseseesesenee
nenenenwneneneneneneneneneseenenenenene
nwnwnwenwnwnwnwnenwwnwsenwnwnwnwnwnwnw
wsewwwwswnwnenwwneenwwwnwsenwwnwse
eseeeswenweneweseseeeeeeeee
nwnwwwnwswnwwwwewnwnwwwwwnwwnw
esesesenesesewseseswsesenee
seswenwnesenweswsenwnewsese
nwnwswnwnwenwenwnwnwnwwnwnwnwnwswnwnwnwnw
seswnwwsesewneseseseeeswseswswsenesenw
wseswnewsewwwseswnenenwneswswne
esweeeeewneeneneneeeeeeee
eeweseswwswswwwnwswnwesenwwnenww
wswswwneswwnwwwswswwsewe
enwswwnwnwnenwnwnwnwnwnwnwnw
nwnwneneneneneneenenenenwnwneseswnwnwnww
wnwnwwwnwnwnwnwsenwnwwwnwenwswnenw
neseseneseewnesesenwseeeseswwseese
swswswwswswswswnewswswswswswswswsww
wwwsewwwnwswwnwnwnwnewnwwwnwnw
enwwwneesesweseeseneswewsesenesesese
esesesesesesenwsenwseseesesesesesesesesww
eweeeeesweeeeeeeenweee
newswseswseseseswsweswswnwneswwswsesw
nenwswnwsenwseswnwnwwswweesesewnenwse
seseseseseswseeswseswseswsenwswseswseswse
seseenewesesesesesesesesesenesesesesw
sweneesewsenwswswseseeeseenwenee
seeweseswnweseseeseeweeeeese
esweseeeeseeeeeewneeeeese
wwwswnwswswswweewswswswswwswwsw
swseswsenesesesesesesesenee
swenwnwnwswnwneswnwnwnwnenwnwnwseeswe
swnwnenwnwnenwnenwnwnwnenenenwnweenwwnw
nwswswenwneseswseenwnesenenewwnwwse
esweewneneeseneswnenee
eeeseneweneneeneeseneneneneneenenew
swneswswwwwswswswswwwwswswswwsww
eeseeweneeeesesese
senenwsenwwnenenwnwwnwnwnwnenwsenwsenenene
eneeenewwsweeeneneseeswneewenw
senwnenewenwnwneswweneneneseeneenesw
eesenweeseesweewewneeeseee
wsenwewnwwwwnwse
nwnwnwsenwnwnwnwnwnwnwnwnwnwnwsenwnwnwnwnw
eeweseneeeeweeneneeeneeenw
eseeeeseeseeseseeseseseenweese
sweeswneseesenenenwswwneneswnweenwnw
nwneenwswnenenenenwnwnwnwnenwnenwnenwnene
wnwnwnwwnwwwnwnwnwwsewnwnwenwswnwww
wwwwnwwwwwwwwwwwwwwenw
wwwswwswsewwswnewnwwwewswwneww
senwswseseesenesewseseseneeswsesesesesese
nwnwswsewsewswnenenwew
newnenwnenwnwneneenenenenenenwnwnenene
wnwnwnwnwnwwnwsewnwwwwwnwwnwwe
swswswswneswswswswswseswswswswswswseswsw
eneneneeneneseswnenenenenenenenewnenene
nwnwnwnwnwnwenwnenenwnwnwnww
nenwwswnwnesewenwnesewwnwsenesewswsw
nwwnenenwneeneneseenewnenwnwnenwnenwne
swswswswswswswswswswwwwsweswneswswe
eneneneneneneneswneswnenenenenewnenenene
eeeneeeeeneewseneeeeeeene
eseseeseneseswwsesesesesewsesesenwsw
nwnenenesenewnenenwnenenenenwnenesenenenene
wnweewswnwswewneswnesenwwewswew
wswswswsenweeeweneeeneewneeesene
eeeeseeeseeeseseeenweeesesw
swswswnwnwenwnwswnenwnenwnene
swwswswswswwwwswwweswwwswswneswsw
wwswwswseneswwwswswswenwsweswsenew
swwswswseswseswswseswswneseswswswseseswnesw
eeneeeeesweeeee
swwswswwswwswwneswwneswswswswswwsw
seesesenwseseseswse
nenwnwnwesweneswnenenenenenenwswne
nwnwwnwnwwnwsenwnwnwwsenenwnw
swseswwnwswswswswswseswswswenew
enweeenwesweeeeeeeeeesenwsw
eswseenwswnwsesesesenwseewwseenesenw
wswseeswneeeneewneneneeenwneeswnw
newnwsenwnenweneeeneesweseeswnw
nwnwwswwnwwwnenwnwnw
wnesenenenwnenenenewnenwnenenesenenene
swswwswsenwswswswswswswsw
sewseswswneseseswseneswswseesesenesese
swwseswwswswswwnwswwwwnewwwwww
wwwnewsewwwwwwwwwwwwwww
newnenwwnwesewnwnwwenwwnwsenwwnwsw
nwwsewwwnweseneneswswwsenewwsenw
swswswwswswnwsweswswseswswswweswswswswne
wswseseswsenwnweseeseswswse
nwnwnwnwnwswnwwnwnwnenenwnwswwnwnwewnw
neswswswseswswsenwesweseneseswwwnwswnwsw
ewwswswwswswswwswswswswswnweswwwsww
eeseeseeseeeeseeeeewseeese
neeeenwneweeeeswseeeneeneee
neenenwswnenesenenenwneneneneneneewwne
neneeeneneneswnenenenenenewnenenenenee
neswnenenenwnwswnwnenenenenee
wwwwenwwnewwwwnwwwwwwwnwsw
nenewsenesweseneeneenwwnenwneswwsw
sewwwnewwnewswwwww
senwnwenwwnwsenenwnwswenenwnwswnwnwsenew
nwnwnwnwnenwnwnwswnwnwnenenwnwne
wswseeenwewnweeeewswseesesese
wwswwwwwwwseneeenewwwwwse
eeeseeeeeneesweeeeeeeese
neesewneneneneeneeeseeeenweneee
seseseseseswseseseseseseswsesenesesesese
senenwnenenenwnenenenenweneswnewnwnenene
sewswwesweewswwnwswswwwwswsww
eeneneeneneesweneeneneneswnenenwe
swneswswsesesesenwswesewwneseswsweswnw
nenesweneeeneeneneneneneneneee
nwwsewnwnwnwwnewnwnwnwwnwwwnwsenw
wnenenwseswneneneswenenwsenwneswnwne
eeeeesweeeeeeeeneeneeee
nwnwnwnwwwnenwswnwnwewnwwwwwnwnww
newnwnwnwnwsenwnwnwsenwsenenwnwwnwnwnwnww
eseseswseseseseseneseseseeswenwesew
wswwwwswwwwwwwwwnwwwsewsw
nwnwnwnwwnwnwnwnwnwwwwnwnwnwwnwnwe
nweneseneneseewnwnenwwseseneneeenee
nwnwnenwnwnwnwnwnwnwnwnwnenwsenwnwnwnwse
seseseseesesesewsenwsesese
sweenweesenwwewsenwswsesweenene
nwswnwnenwenwnwnwnwneeswenwnwnwwnwnwne
nenenwwnenesenesenenenenenenesenenewswnw
senweswnweseesweeesenwseenweenw
seswsweseswewswnwnwswswseswnwseswswne
enwnenwnwnwnwsewnwnwswwnwnewnwsew
eneeneweneeeeeeneeeeenweesw
seseseseenweseswwewneeew
neenwsesweeenesweeee
nweenenenwneneseswesweeneneneneene
eseeeeesenweeesweeseeseeseee
nwnwnenwnwnwsenwnwnwnwnwnwnwnenwnwnwnwwnw
seseseswswswswseswnwswsw
eeswenwneneeeeneneeneeeeeenene
wnwnwnwwwnwwnwnwwswe
esenenenenenenwneeswnwnwnenenenwnwwnw
seseseswsesenesesesesewse
nwnwswnwswwnwnwnwnwnwnwnwwnwenwnwwew
seseseeeeeesweeseeseene
seeswwwneeswswnesweswswwenwswnwsww
nenenwnwnwswenenenwnwnenwnenenwnwnwnwne
swseswswwswswswnwnwnwseswwwwewwsw
neenwseeneesesenewneenwnwneeenwsesw
wswswswseesenwneswnwswseseneseswwswswsw
swenesenesesenwswsesweswwnwswnwwsenwsw
nwnwnenenwnwnwnwnenenenwnwnese
swswseswseeswsweswswseseseswswswwnwswswse
swswsweswwwswswswsweswswseswswswswsw
nwnwsenwwnwnwnwsenwnwnwnenwnwnenwnwwnene
nwwnwnwnwwnwwwwwwwnwewwewww
swwswswseswswswswswswsweswswswswswswsw
nesesesesenwewswnwsesesesesenw
seseeeseseeseeseeeesenwseseeswwe
swseswswswswseseswsenwnwswsw
swswwwwwewswswewnwnwnwswewwsw
swswnewswswsenewswnenwneeesenwswwsw
swswswswswswswswswswswswnewswswswwswsw
eweseeenwseseeseeseseeseseseee
sewseseswesewseseneseswswseesenwnwsw
wswwswwwwwnwswswswsenewwswwswww
nwnwnenwwnwwwwwnwwnwwwnewswnwsw
neseswwsenwnwswwsenwneesenene
sewewwswwwswswwsewnwneswswwwnw
nenenewnewsweeeeeseswswseenwnee
wwwnwnwneseswewswwswseswwswenewsw
neswsewswswswwswwswswswwwswswsw
nwnwnwenwwnwenwsewenwnwswwwnwnwnwnw
nwnwnenenwnenwnwnenewnwseneswnwnwseenwnw
neweeseenwseeeeeeseseenwneeew
seswnwnweseweeswnwnewnesweswnenenw
eneewneneeneeneenenwnesweeseene
eenwsweeneneneneeeneeneeeneenene
neneswnesweneenewneseneswnenwnenwwse
swneswswsesewwseswseswswswseneswswwswne
nwnwnwnwnwnwnenwnwnwnwnenwnwswenwnwnw
wswwswwwnewswsenwwwswswsewwswsw
wsewwwwwwwwewwnwwwwwww
seswsweseswswnwswsesenwseseseswwseswse
wwwswwswwwswswswswswswwswswswew
swswseseswswsesesenwneswswswseseeseswwsese
enwswnwnwnwnwneneneeswnwneeswnewnwnenw
swswsewswswnwswnwneswswwwwnwwewse
newneeneneneneneenenenenenewnewenese
nwnwnewnwewenenw
swwnesenwseneneswnenenenwnw
eeeeeeeneeeeeseweeneeene
swswswwwsesewswswswwwnwwwswwswwne
ewsenwwewwewnwwwwwwnewwww
nenewneeneenenenenewneneeneneneseneene
swswsewseswswseswweswswswswneswswseswsw
swseswseswsesenwsweswwseswseswseswenese
swewwnewseswnwwwwswswwwsewnene
seenesesweseenwnwseseesesewsesesweese
nwswsenwenwnwnwswnwewnwnwnwnwnwne
wsewwnewwwwwnwswwwewwwnw
eeeeenwswnwswee
wswwwwwwwwwwsenewwwwwwww
nenenenwseseneeseneneneeswnwesenwnwnwse
eneswswsweweseswswsenwswswswwwnesese
nenwnwnwsenwnewnwnwnwewenwnenwnwnwnwnw
newnwswwwwwnewswsewwwwwwswswne
sewseneseseseseseseseseseeseewsesese
enenenweeneeeeneneneeeneeneeesw
esweeeneeseeeesweeeseswnwnwenw
seseswsweeswswwseseswswseswseswsesenw
nenwneneenwnenwnwnenwneneneeswneneneneswnw
nwnenenwnwswnwnwnwnenwnenwnwnwnwnwneswne
ewnewnwswswweeswwewnwenenewwswse
eeesweseenwenwesweweeeeseswne
nenwswnenewwnweneneswewneneeneneswnee
swseseseseeswseseswseseswsenwseswsesenw
eneseeeswseseesesweeenwse
enenenenwwnwneenewnenwnenenwswnwsesenw
wswwswswswswnwswsweswwswswswswswswswsw
nenwneswnenenenenenenenenesenenenenenenene
swnenwnenewsewneneneneneneseeneenenenenw
wwswwnewswswwwwwenwsw
seeeseeenwneseseseeeeeewsesese
seneseseseswseseseswnwswseseswsenenewsw
swseseeswseswswswseswswwswswswswswswsw
nwnenenewnenenwneenenwseseneneneswnewne
newneneneneneneneenenesenenenenwnenew
eeneeeeweeneneeeeeeeeswenwsw
nwesesweseseswsesewsesesesesesesesesese
wesweeweewswwnenweeneenesenene
swswnewswswwnweneseseseneseswwwseesw
wwswnewnenwswswswwewwwswswnewwse
neswseseseseseswseseseswswsesesw
neneneneneneswnenenenenenenenenwnene
wnwenwwnwnwnwnwwnwnwwnwnwwwnw
senwneswnenenwnwseneneswnenwnenewnwnenee
newwwnewwwwwwsewwswwsewneww
nwsenenenenwswnenenwsenenenenwnenenenene
eseeseeseseseeseweseseeseesesee
wswswwneewnwnwsewwwnenewseneswww
eeseeeeeeeeeeeneeeeeew
senwwneneswnesenwsewnenwnwnwnenwnwnew
sewneseseseneswswswswswsweseseswseswwsw
eseseeneseeewneenweeenwnwswenee
swnwneswweneeneewneswsenwesenwesee
neneswnenenwnwnenenenenenwswneneeswnene
eeseseeesewsesee
seseesenwswseseseswsese
neenwseeenwsewwwseesenesesesesesw
enweseneeeneneenewenewenwswese
wwwsewwwswewwswwwnwswwwswsw
swnwnwwseewnwnwwswnwwnwnwwnwwwnewse
seseseseeseseseseseseeswenwseesesesese
neneneneneneeneneenenenenewneeneee
weenwnenwwsweseseswnwsee
sesewwwnwwwnewwww
neewewneeneweeeeeeneenesenene
nwwnwwsewnwnwnwnwnwwnwnwwnwsenwnwnwnw
senwnwnwseseseseswwsenwsesenwseneesenw
wewswwswswswwswswwwwsww
nwseneseswwnwswnwseseenwewseeeenwsee
neneswnenenenenwnenesesenenesenenenwnenw
nwneneeeswnewsenweenenenweswne
eeenwneswseenewswnwneenwseneneeeee
neneneeeneseesenewneenwwneneneneswne
swswswswswswswswswswswswswswswswneswswsw
enweeeseeseeeenwswweeeeeee
wenwnewseenwnwneweenwnwnewnwnwnwnw
swswswsweswwwswswwnewswwswwwseww
nwwnwnweseswnwwswnenenwnwnwwswewnw
wnewwwwsewwwewwwwwwswww
swseswswswwswswswswseesweswswsesenwsw
sweswnwseeswswseswwswnwswswswswneswsw
wwswswseswwneneswseswswwswnwwswseww
sweswswswswseswswswswswswesweswwswnwwsw
sewnenwnenwswnwswenenewnwnenwseewnw
wnwwneenesewneeneenwnesewnewnwnenene
seswswswneneswswswseswswwswesenww
swswswwseneswswwswseswswswswesw
nwwnwnwwwnewwwsewnwnwnwnwnwsenenwnww
seseseswseswswseseseswseneeseseswswsewsw
eeneweseseneesesweseeeeseeseese
swseswswseseswswnenweseswswseswseswsenw
wwwwwwwwweswewwwwwwwnew
swseswswswswswswswseseseswswswswwneswswsw
wwwswwwwswwwwwwwwnewsesww
nenenewneneneneneneneeneswnenenene
nenenwneneneneneneewneneneneneswnwnene
nwneeneneneneeeneeeswneswenwswneswse
nesenwseeseswneseesenwsesesweneeesesw
swwswwswwwseswwwwnwwswsewneww
wwwwwwwsewwwnew
eenwesweeeeweneneeseneeewee
swsenwswnwwwswneenwwnwnwenwenenwnw
swnesweswnwswneenwsesweneneswnwnwnwnw
ewswwnwseswsenewnewwsweeneneneese
sweseneseswnewenenwnwwswseseseseswsene
nwnwnwnwwsenwnwwwnwnwnwnwwneewnwnw
nwnesenenwnwnenenwnwnenwwnenenenenwnene
nwnwswnwnwnwsenwnwnenwnenwnwnenwnenwnwnwnw
wsenwwenwnwwswwnenwwewnwnwnwwwse
wwswswnewwswwwwwwwswwweww
wswswwswswwswnwswswswswseswswswswsww
wwnwwewnwnwnwnwnwseeswwww
eeeeeeeeeesweeeeenwseeeew
eewneseenesenweneswseseeeweee
swwwswswwswswswswseswswwswnwswswwsw
nweeeeneneeeeseweweesweeeene
weewneweswnwwsenenenenenwesene
sesenwseseseseeweseeseswenwsenwsee
esweeeeeeswnenenwenweeeeee
wswswwnwswswwswewnwswswswswswswswewsw
sweswswswswswnwswseseswswseseswswswswsw
nwewseeseeeneswswseeweseeeneenw
eseswnwneneeneneeenwneneenee
swwswswwneswsewswnwnwwseeswwwsew
neesewweneseseswnwnewnweneswnwneswnee
nwseswseswswswswnwswsweswwswseseswswe
wnwwwsewnwenwwwswnwwnwnwwwwww
eseseseeneesesesenesewsesewsesesewse
swnwnwswnewwenwnwnwnwwwnwnenwnwwsww
nwnwnwnwnwnwnwenwnwnwnwwnenwnwsewsenew
neseswseswwseseswenwnwswseswseseesew
nwwnwnwnwnwswesweeenwnwswseeswnwnw
eeeeeeseeeeeesenweeeesese
nwenwwnenwnenenwnwnwnenwnwneneswnw
nwswswseswnwsesenwseseswswse
swseswneswsweseswseswwwswswswnwswswswsee
enwsesesesewseeseeeseseee
wenenesesesewnwneneswnwsweweneeswenw
sewwswswnewsewewswswwwswswnenesesww
seewseseeseseseseseneseseeeeeeee
nwnwnwnwnwenwswnwnwnwnwnwenwnwnwnwnww
swswswswswwsweneswswswnwswswswswswswswse
neneeneeneneneswnenenewnenenenenenene
nenenwewnenenwnene
sesesewseseseseseswseseseswnesesenesew
nwnwnwwnewseenwnenwswnwswnwneneneene
eseeeeseseenwesweeeenweeswee
neswwnewswsewswwseswswswswwwnwseswswsw
nwnwnwnwnenenwnenwnwneswneenwnwnwnwseswsw
wswwwwwswewswwwwnewsewswwnw
nwwneenenenwnwneenenwnenenesenenwnesw
wwewwnwwswewswwwneewwneeww
wswnweseseseseswseseswsesesenesesenese
wnwewnenwnwwnesenwnwnwnwsenwnwnwnwnwnwse
seenewswswswswsewswswswseseswswswswsese
eweseswseeeenweeeeeeeeeee
eswsenwneswswswswwnwswneswneseseenwnenw
nenwnwnenenwnenesenwnw
neneneneneneeswnenwneneseneneenwsw
nwwnwwwwnwwnwnwwnwwe
neeneswsesesesenesenesewseseswesenwsewse
seenwswsweeswswswswwwnwseswseswsee
sweswnewwwswnwnwewswwswwswswwww
eewneenwneeeeswneeseseeee
wewwwwwwwwwwewwwwwwww
nwsweneneneewnwnenwnenenwnwnwne
nenwneneeneswenenewneneseneswwnenenene
swnwseswseswswseswswseswswswseswswswsese
wnwwnwnwnwneenwnwnwnwnwnwnwenwnwnwnw
wwswnwnewenwwswswwnewwwwwwwne
neewnwnwwnenenesweneneeenwseneneswnwne
eneswnenwswnwnenwnwnwne
wswnenewneswwswwwseswneswswnewswnenw
eseeseeeseseenweeeenweeeeeswse
eswsenweneeeeeneeeweneeneneeene
nenewnesesenenenenewsenenwnwne
newwwnwwnwnwnwwwseswwwwnwnwnenwww
nwnwnwnwnwenwnenwnwnwwnwnwnwnw
swswswswswswswswnwseswswseswswswswswsw
nwnwwsenwnesenwnenwnwnwnwnwwswwnwww
senenwswswswwswswswswswswswswsewswswswsw
nwwwwwwwsewwwwwwnewwwe
wnenwswnenweswnewnwnwenwnwswnwnweesenw
nweseeeswenewseeeneeeweswneenwe
eswnwseswnwswswswewswswwswswswswsww
swsesesenwsenwswswsewneseseseenwsw
seseseswseseneseseseseswswseswseswneswse
nenenenenwsenwsenwswsewwwwwswnwenwse
neeneneneseneneneeeswnweneeee
eeneneeneneswneneenweneswnenenenewne
esenwwswwnwswewwwswswswswnwwwsw
wwwseseswnwnwneeenwwnewswnwswwwe
wswseswseswswswswnwswswsweneswswswsesw
nwswnwwwnwnwenwnw
swsesenwneseseseseseseseseseeseseesese
swsenewwsewnwwwwswewwneewwse
wwsweswnwnwnwsenesewswneneneseewne
nwnwnwnwnwnwnwswnwnwnwnwnwnenwnwsewnwnwne
swseswswsesewswsesweswswswswswswseswsw
nwnesewnenenenenesenenenenenenenene
nwnwnenwwnwnenwnwnwnwnwnwnwnenenwnwnwnwse
neeesweneneenee
eeseseseneswweeesesenweeesenweenw
wswwswswwwwwwwwewwwswweww
seseseesesewsesesewsesesesesesenesese
nwnenewseseneswneneweeswnenesenwewne
neseeneneneseenenenenenenenenwewnenee
seseseswseseseseseswesesenwswseseswsesw
swswsenenwewneseeeneeeneenesenwwe
sewwwnesesenwwnewwwwwwnww
nwseesweseswseswnwwsesweswsenwnesenenw
wwneseseeeseseeseseseseseneewseseee
nenenenwnenwnwnwneenwnewwneenenenwnw
sweeneeeeeeneeeeeeswneeee
wseeswwswwwwwsweswwnwswswswswww
eneneneeneswneneeneswneeneneneeee
enenenenenwnwwswnenenese
swnewnweseseewneneeswswswwnweww
seswsesesesesesesesesesesesenesesesesese
wswswswswseswnewswneswwwswswneswewsw
wnenenenenwnenwwenwnwsenwnwnwnenwnw
seseeeeeweeeeeeeenwseesesese
eeeesweeeeneeseeenweesewesene
swnewswneswwseneswwswneswswswenwswse
nweneeneneneneneneesenwswswenenesenww
seneneneeenenenenenenwneneneeeenene
swwswswswswswwwwswswswweswwswsww
nenwneswnenenwnenenenenesenenwneneenwnwne
swswswsweswswnwswswswswswswswswswswswsw
sesewnenwnenenwnenenwneenenenwnwnwswnenwnw
sesenwseseseseseseseseseeseswsesesesese
seseseesenwsenwseseswseseseseseswsewnese
wwswnwwswwwwwwwwwneewnwww
eeeseswsesesesenwnweseweese
neeeseeeweneeeeeneenwswnwnesw
wnwnwwwnwnwnwewswnenwwwwwswwnw
swnwseseswwswneseswneseswswswseseeswsw
eswnwnwswswwswswswswsweneswseswswneswswsw
nwseseeseseseseesesesesesee
seswseswswewwswnewnwswwwswnwswww
wwwwwnwnwnwnwnwewswnwwnwwnwnww
neseswnwswswseswseseseswseswseswseswswsesw
""".strip()

from typing import List, Set, Tuple
from collections import Counter


Position = Tuple[int, int]
Tiles = Set[Position]


changes = {
    "e": (0, 1),
    "w": (0, -1),
    "a": (-1, 1),  # se
    "b": (-1, 0),  # sw
    "c": (1, 0),  # ne
    "d": (1, -1),  # nw
}


def get_line_pos(line: str) -> List[int]:
    pos = (0, 0)
    for char in line:
        pos = (pos[0] + changes[char][0], pos[1] + changes[char][1])
    return pos


def get_positions(text: str):
    positions = []
    for line in text.splitlines():
        positions.append(get_line_pos(line))
    return sorted(positions)


def remove_doubles(positions):
    counts = Counter(positions)
    return {pos for pos in positions if counts[pos] % 2 == 1}


def test_part1():
    text = data
    text = (
        text.replace("se", "a").replace("sw", "b").replace("ne", "c").replace("nw", "d")
    )
    positions = get_positions(text)
    non_flipped = remove_doubles(positions)

    assert len(non_flipped) == 521


def gather_neighbors(black_tiles: Tiles) -> Tiles:
    return set(
        (tile[0] + offset[0], tile[1] + offset[1])
        for tile in black_tiles
        for offset in changes.values()
    )


def count_black_neighbors(position: Position, black_tiles: Tiles):
    return sum(
        (position[0] - offset[0], position[1] - offset[1]) in black_tiles
        for offset in changes.values()
    )


def game_of_life(black_tiles: Tiles, steps: int):

    for i in range(steps):
        all_neighbors: Tiles = gather_neighbors(black_tiles)
        all_tiles: Tiles = all_neighbors | black_tiles
        new_black_tiles: Tiles = set()
        for tile in all_tiles:
            if tile in black_tiles and count_black_neighbors(tile, black_tiles) in (
                1,
                2,
            ):
                new_black_tiles.add(tile)
            elif (
                tile not in black_tiles
                and count_black_neighbors(tile, black_tiles) == 2
            ):
                new_black_tiles.add(tile)
                pass
        black_tiles = new_black_tiles

    return len(black_tiles)


def test_part2_small():
    text = test_data
    text = (
        text.replace("se", "a").replace("sw", "b").replace("ne", "c").replace("nw", "d")
    )
    positions = get_positions(text)
    tiles = remove_doubles(positions)

    assert game_of_life(tiles, 1) == 15
    assert game_of_life(tiles, 2) == 12
    assert game_of_life(tiles, 3) == 25
    assert game_of_life(tiles, 4) == 14
    assert game_of_life(tiles, 5) == 23
    assert game_of_life(tiles, 6) == 28
    assert game_of_life(tiles, 7) == 41
    assert game_of_life(tiles, 8) == 37
    assert game_of_life(tiles, 9) == 49
    assert game_of_life(tiles, 10) == 37

    assert game_of_life(tiles, 20) == 132
    assert game_of_life(tiles, 30) == 259
    assert game_of_life(tiles, 40) == 406
    assert game_of_life(tiles, 50) == 566
    assert game_of_life(tiles, 60) == 788
    assert game_of_life(tiles, 70) == 1106
    assert game_of_life(tiles, 80) == 1373
    assert game_of_life(tiles, 90) == 1844
    assert game_of_life(tiles, 100) == 2208


def test_part2():
    text = data
    text = (
        text.replace("se", "a").replace("sw", "b").replace("ne", "c").replace("nw", "d")
    )
    positions = get_positions(text)
    tiles = remove_doubles(positions)

    assert game_of_life(tiles, 100) == 4242
